{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bmit",
    "module": "hj-voice",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "hj-voice-1.1.aar",
          "url": "hj-voice-1.1.aar",
          "size": 19190,
          "sha512": "bfcb0fd273eaaceb27adb4caa938ad574dfd0532c57d506e3b0f73f0646d1efcfc9b77d483a8e6e71048c470d39832c3e3633a104dfb63c39eb50e2d0af2c1ed",
          "sha256": "829f46b196d4473a5316d6456c0865d21d176e9a0c300bbd1387dfb17b189722",
          "sha1": "2939e5ee895afcfc2df0f5896a9c36cc34b1bb34",
          "md5": "f1fd662c9bade317b5a63aa86e0cb355"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "hj-voice-1.1.aar",
          "url": "hj-voice-1.1.aar",
          "size": 19190,
          "sha512": "bfcb0fd273eaaceb27adb4caa938ad574dfd0532c57d506e3b0f73f0646d1efcfc9b77d483a8e6e71048c470d39832c3e3633a104dfb63c39eb50e2d0af2c1ed",
          "sha256": "829f46b196d4473a5316d6456c0865d21d176e9a0c300bbd1387dfb17b189722",
          "sha1": "2939e5ee895afcfc2df0f5896a9c36cc34b1bb34",
          "md5": "f1fd662c9bade317b5a63aa86e0cb355"
        }
      ]
    }
  ]
}
